[package]
name = "quad-col"
version = "0.1.0"
edition = "2024"

[dependencies]
shipyard = { workspace = true }
hashbrown = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
rand = "0.9.1"
imageproc = "0.25.0"
image = { version = "0.25.0", features = ["png"] }